// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AutoLocatePath():Promise<main.LocateResult>;

export function BrowseFolder():Promise<string>;

export function InstallBepInEx(arg1:string):Promise<void>;

export function InstallSLP(arg1:string):Promise<void>;

export function OpenFolder(arg1:string):Promise<string>;

export function ValidatePath(arg1:string):Promise<string>;
