// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AutoLocatePath() {
  return window['go']['main']['App']['AutoLocatePath']();
}

export function BrowseFolder() {
  return window['go']['main']['App']['BrowseFolder']();
}

export function InstallBepInEx(arg1) {
  return window['go']['main']['App']['InstallBepInEx'](arg1);
}

export function InstallSLP(arg1) {
  return window['go']['main']['App']['InstallSLP'](arg1);
}

export function OpenFolder(arg1) {
  return window['go']['main']['App']['OpenFolder'](arg1);
}

export function ValidatePath(arg1) {
  return window['go']['main']['App']['ValidatePath'](arg1);
}
